"use client";

import Container from "@/components/common/container/container";
import Image from "next/image";
import Link from "next/link";
import teamOne from "@/assets/images/service-img/digital-team-1.jpeg";
import teamTwo from "@/assets/images/service-img/digital-team-2.png";
import teamThree from "@/assets/images/service-img/digital-team-3.jpeg";
import teamFour from "@/assets/images/service-img/digital-team-4.jpeg";

const services = [["⌕", "Search Engine Optimization", "Technical fixes, content strategy, and authority-building that help you show up when the right people search — and keep showing up over time.", ["Technical SEO", "Content", "Link Building"]], ["↗", "Google Ads (PPC)", "Search and shopping campaigns built around intent, so your budget goes toward people who are ready to act — not just browsing.", ["Search Ads", "Shopping", "Performance Max"]], ["◎", "Meta & Paid Social", "Facebook and Instagram campaigns built to stop the scroll and turn attention into leads, purchases, or long-term brand loyalty.", ["Facebook Ads", "Instagram", "Retargeting"]], ["◌", "Social Media Management", "Consistent, on-brand content and community management that keeps your audience engaged between purchases and builds lasting trust.", ["Content Calendar", "Community", "Reels & Stories"]], ["✦", "Campaign Creative & Content", "Ad creative, copy, and content produced specifically for what's live in-market — designed to convert, not just to look good.", ["Ad Creatives", "Copywriting", "Video Ads"]]];
const studies = [["Z", "ZanduCare Wellness", "D2C Health & Wellness", "+340%", "Website Traffic", "+180%", "Qualified Leads", "Scaled a holistic wellness brand's D2C revenue through a full-funnel Meta Ads strategy, conversion-focused creatives, and a landing page optimisation pass.", ["Meta Ads", "Creative Design", "Content Strategy"]], ["S", "SolarCo Industries", "B2B Manufacturing & Energy", "4.6x", "ROAS on Google Ads", "−38%", "Cost Per Lead", "Rebuilt Google Ads around buyer intent, moving a solar manufacturer away from broad-match chaos into a campaign architecture that could scale.", ["Google Ads", "SEO", "Web Design"]], ["A", "AdTrack", "SaaS & Technology", "3.2x", "Pipeline Growth", "+220%", "Demo Requests", "Built a connected acquisition system that paired performance campaigns with conversion-focused messaging and reporting the sales team could use.", ["PPC", "Landing Pages", "Analytics"]]];
const team = [[teamOne, "Nikesh Kuchhal", "Performance Marketing"], [teamTwo, "Rohan Sharma", "Growth & Performance Marketing"], [teamThree, "Priya Mehrotra", "Creative Strategy"], [teamFour, "Arjun Verma", "Paid Media & Analytics"]];

export default function DigitalMarketingPage() {
  return <main className="digital-page overflow-hidden">
    <section className="digital-hero"><div className="digital-hero-glow" /><Container className="common-container relative z-10 grid items-center gap-12 py-36 lg:grid-cols-[1fr_0.86fr] lg:py-44"><div><p className="digital-kicker">Strategy · Creative · Performance</p><h1>Digital Marketing Built <span>Around Your Growth.</span></h1><p className="digital-hero-copy">We build high-performance marketing systems that generate leads, drive conversions, and scale revenue consistently — running every channel as one connected strategy, not a collection of disconnected tactics.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/contact" className="digital-button">Get Free Audit <span>→</span></Link><a href="#work" className="digital-button digital-button-outline">See Our Work <span>↓</span></a></div><div className="digital-stats">{[["50+", "Brands Scaled"], ["3.8x", "Average ROAS"], ["+321%", "Client Growth"]].map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div></div><div className="digital-hero-cards"><Outcome icon="↗" value="+340%" label="Organic Traffic Growth" /><Outcome icon="◉" value="4.2x ROAS" label="Paid Campaign Revenue" /><Outcome icon="✦" value="+321% CPL" label="Cost Per Lead Reduction" /></div></Container></section>
    <section className="digital-light digital-section"><Container className="common-container"><SectionHeading kicker="What we do" title={<>Services Built For Your <em>Growth</em></>} text="Every channel. One strategy. Planned and run as a connected system — not a collection of separate tactics." /><div className="digital-services">{services.map(([icon, name, description, tags]) => <article key={name}><i>{icon}</i><h3>{name}</h3><p>{description}</p><div>{tags.map(tag => <span key={tag}>{tag}</span>)}</div></article>)}</div></Container></section>
    <section id="work" className="digital-dark digital-section"><Container className="common-container"><SectionHeading dark kicker="Proof of work" title={<>Recent <em>Projects</em></>} text="A selection of brands we've helped grow. Real campaigns, real results." /><div className="digital-study-grid">{studies.map(([letter, name, industry, one, oneLabel, two, twoLabel, copy, tags]) => <article className="digital-study" key={name}><header><b>{letter}</b><div><h3>{name}</h3><p>{industry}</p></div></header><div className="digital-study-results"><Metric value={one} label={oneLabel} /><Metric value={two} label={twoLabel} /></div><p>{copy}</p><div className="digital-tags">{tags.map(tag => <span key={tag}>{tag}</span>)}</div><a href="#featured">View Case Study →</a></article>)}</div></Container></section>
    <section id="featured" className="digital-featured"><Container className="common-container"><p className="digital-kicker">Featured growth story</p><h2>From 0 to 1, Then 1 to <em>100.</em></h2><p className="digital-featured-intro">Kunjika India had traction and a great product. What it needed was a connected growth system — and a team that could build it, run it, and keep improving it.</p><div className="digital-phase-grid"><Phase number="01" title="Building the Foundation From Scratch" copy="Before a single rupee went to spend, we set the basics: a clear brand identity, a conversion-ready site, and creative that made people stop scrolling." bullets={["Brand positioning & competitor research", "Shopify store, landing pages & conversion setup", "Meta pixel, Google Ads tracking & reporting"]} /><Phase number="02" title="Scaling What Worked. Fixing What Didn't." copy="Once early campaigns had real data, we restructured the account, layered in high-intent search, and scaled the winning creative." bullets={["Google Shopping + search for high-intent buyers", "Meta Ads scaling with retargeting", "SEO and lifecycle email flows"]} /></div><div className="digital-featured-stats">{[["+340%", "Organic Traffic (6 Months)"], ["4.1x", "ROAS on Meta Ads"], ["100+", "Orders in First 60 Days"], ["−29%", "Cost Per Acquisition"]].map(([value, label]) => <Metric key={label} value={value} label={label} />)}</div></Container></section>
    <section className="digital-lavender digital-section"><Container className="common-container"><SectionHeading kicker="Our process" title={<>No Campaign Goes Live Until We Know <em>What We&apos;re Aiming For</em></>} text="Three phases. One integrated system. Built around your numbers from day one." /><div className="digital-process">{[["01", "Discover & Strategize", "We start with your customers, offer, audience, competition, and past performance — then turn it into a clear plan."], ["02", "Launch & Manage", "Campaign setup, creative production, and continuous optimisation around what the data says is working."], ["03", "Measure & Scale", "Reporting against the metrics that actually matter. We improve what's working and fix what isn't."]].map(([number, title, copy]) => <article key={number}><b>{number}</b><h3>{title}</h3><p>{copy}</p></article>)}</div></Container></section>
    <section className="digital-dark digital-section"><Container className="common-container"><SectionHeading dark kicker="Our toolkit" title={<>Platforms & Tools We <em>Specialize In</em></>} text="The best results come from knowing each tool well enough to make it work with the rest." /><div className="digital-tool-list">{["Google Ads", "Meta Ads", "Google Analytics", "Search Console", "Looker Studio", "HubSpot", "Klaviyo", "Mailchimp", "WhatsApp Business API"].map(tool => <span key={tool}>● {tool}</span>)}</div></Container></section>
    <section className="digital-light digital-section"><Container className="common-container"><SectionHeading kicker="The people behind the growth" title={<>Meet The <em>Team</em></>} text="Senior strategists, creatives, and analysts who see what works — and what doesn't." /><div className="digital-team">{team.map(([image, name, role]) => <article key={name}><Image src={image} alt={name} /><h3>{name}</h3><p>{role}</p></article>)}</div><SectionHeading kicker="Why Purple Brick Digital" title={<>What Makes Us <em>Different</em></>} /><div className="digital-difference">{[["Strategy Before Spend", "We don't launch a campaign until the audience, offer, and measurement plan are clear."], ["One Team, Every Channel", "Paid, creative, content, and conversion work together as one growth system."], ["Reporting You Can Actually Use", "Clear numbers, no jargon. You'll always know what's working and what needs attention."], ["Built Around Your Business", "No cookie-cutter packages. We build around your stage, budget, and goals."]].map(([title, copy]) => <article key={title}><i>✦</i><h3>{title}</h3><p>{copy}</p></article>)}</div></Container></section>
    <section className="digital-faq"><Container className="common-container"><SectionHeading kicker="Got questions?" title={<>Common <em>Questions</em></>} /><div>{[["How do you decide which channels are right for my business?", "We start with your audience, offer, sales cycle, and the data you already have. The plan is built around the channels most likely to create measurable momentum."], ["How long before I see results?"], ["Do I have to sign up for all services, or can I start with one?"], ["How do you report on performance?"], ["Are there long-term contract commitments?"]].map(([question, answer]) => <details key={question} open={Boolean(answer)}><summary>{question}<span>+</span></summary>{answer && <p>{answer}</p>}</details>)}</div></Container></section>
    <section className="digital-cta"><Container className="common-container text-center"><h2>Let&apos;s Build A Marketing Plan<br />Around Your Numbers</h2><p>Tell us where you&apos;re starting from and we&apos;ll show you what a connected strategy could look like. No obligation, no fluff.</p><div><Link href="/contact" className="digital-button">Get Free Audit →</Link><Link href="/contact" className="digital-button digital-button-outline">Talk To The Team</Link></div></Container></section>
  </main>;
}

function SectionHeading({ kicker, title, text, dark = false }) { return <div className={`digital-heading ${dark ? "digital-heading-dark" : ""}`}><p className="digital-kicker">{kicker}</p><h2>{title}</h2>{text && <p>{text}</p>}</div>; }
function Outcome({ icon, value, label }) { return <div><b>{icon}</b><p><strong>{value}</strong><span>{label}</span></p></div>; }
function Metric({ value, label }) { return <div><strong>{value}</strong><span>{label}</span></div>; }
function Phase({ number, title, copy, bullets }) { return <article className="digital-phase"><p>Phase {number} — {number === "01" ? "0 to 1" : "1 to 100"}</p><h3>{title}</h3><span>{copy}</span><ul>{bullets.map(item => <li key={item}>{item}</li>)}</ul></article>; }
