"use client";

import Container from "@/components/common/container/container";
import Link from "next/link";

const painPoints = [
  ["◌", "Spending On Marketing But Cannot Track What Is Actually Working", "Campaigns are running, spend is going up — but the attribution is a mess and the ROI is unclear."],
  ["↗", "Growth Has Plateaued And You Cannot Identify Why", "The same strategy that worked six months ago is no longer delivering, and you are not sure which variable changed."],
  ["◎", "Launching On A New Platform And Need A Playbook Before You Spend", "Amazon, Zepto, Instamart, LinkedIn — new platforms need new strategies. Start right, not by burning budget."],
  ["◇", "Your Agency Is Executing But There Is No Real Strategy Behind It", "Things are happening, but they feel disconnected. No clear direction, roadmap, or sense of where it is all going."],
  ["✦", "Need Clarity On Which Channels To Prioritize For Your Budget And Stage", "Limited budget and multiple options. Get a practical answer built for your business right now."],
  ["↑", "About To Scale And Want To Avoid Expensive Mistakes", "You have momentum and do not want to waste it. Get the plan before you multiply your spend — or your team."],
];
const consultingServices = [["01", "Performance Diagnostics", "A full audit of your marketing stack — what is running, what is leaking, and where budget is going to waste. We look at every active channel with fresh eyes and real data."], ["02", "Funnel Audits", "We map the customer journey from first touch to final purchase, finding where prospects are dropping off and what needs to change at each stage."], ["03", "Marketing Roadmaps", "A structured, prioritised plan for the next 90 days, six months, or a year — built around your budget, audience, and business stage."], ["04", "Scaling Strategy", "When what works today stops scaling tomorrow, we find the next lever without breaking what is already working."], ["05", "Revenue Optimization", "We connect marketing activity to business outcomes, identify high-leverage actions, and restructure where needed."]];
const steps = [["01", "Discovery Call", "We start by understanding your business, goals, current state, budget, and what success looks like. No assumptions."], ["02", "Audit & Diagnosis", "We go deep into channels, analytics, campaign history, tracking, and competition to find what the data is hiding."], ["03", "Strategy & Roadmap", "You get prioritised actions, channel recommendations, KPIs, and a timeline specific to your business."], ["04", "Review & Handoff", "We walk through every finding and recommendation, so you leave with total clarity on what to do and why."]];

export default function ConsultingPage() {
  return <main className="consulting-page overflow-hidden">
    <section className="consulting-hero"><Container className="common-container grid items-center gap-12 py-36 lg:grid-cols-[1.15fr_.85fr] lg:py-44"><div><p className="consulting-kicker">Marketing Strategy & Consulting</p><h1>Clarity Before Campaigns.<br /><span>Strategy Before Spend.</span></h1><p className="consulting-tagline">No guesswork. No generic advice. A plan built around your numbers.</p><p className="consulting-copy">Whether you are launching a new brand, scaling an existing one, or trying to understand why your marketing is not working — we bring data, experience, and a structured approach to every challenge. Across every platform.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/contact" className="consulting-button">Get Free Consultation →</Link><a href="#process" className="consulting-button consulting-outline">See How We Work</a></div><div className="consulting-proof">{[["50+", "Brands Consulted"], ["15+", "Platforms Covered"], ["100%", "Senior-Led"]].map(([number, label]) => <div key={label}><strong>{number}</strong><span>{label}</span></div>)}</div></div><div className="consulting-insights"><Insight title="Performance Gap Found" text="Google Ads ROAS sitting at 1.4x against a break-even of 2.8x. Budget reallocation needed immediately." /><Insight title="Untapped Opportunity" text="Zepto & Instamart Ads unactivated for this D2C brand. Category demand is high, competition is low." /><Insight title="Roadmap Recommendation" text="Shift 30% of Meta budget to retargeting. Current top-of-funnel spend is not being captured at conversion." /><Insight title="Tracking Gap Identified" text="No GA4 conversion events configured. Fix this before scaling spend." /></div></Container></section>
    <section className="consulting-light consulting-section"><Container className="common-container"><ConsultingHeading kicker="Sound familiar?" title="Is This You?" text="If any of these situations describe your business right now, a consulting session is exactly what you need." /><div className="consulting-pain-grid">{painPoints.map(([icon, title, text]) => <article key={title}><i>{icon}</i><h3>{title}</h3><p>{text}</p></article>)}</div></Container></section>
    <section className="consulting-dark consulting-section"><Container className="common-container"><ConsultingHeading dark kicker="What we do" title="Our Consulting Services" text="Five distinct services — each designed to answer a different strategic question your business is facing." /><div className="consulting-service-grid">{consultingServices.map(([number, title, text]) => <article key={number}><b>{number}</b><h3>{title}</h3><p>{text}</p></article>)}</div></Container></section>
    <section className="consulting-scope consulting-section"><Container className="common-container"><div className="consulting-scope-head"><div><p className="consulting-kicker">Our scope</p><h2>We Consult Across<br />Every <em>Channel</em></h2></div><p>From established global platforms to emerging Indian quick-commerce channels — wherever your customers are and your brand needs to grow, we can guide you. If the channel you need is not listed here, bring it to us.</p></div><div className="consulting-channel-groups"><ChannelGroup title="Paid Advertising Platforms" items={["Google Ads", "Meta Ads", "LinkedIn Ads", "YouTube Ads", "Amazon Ads", "Zepto Ads", "Instamart Ads"]} /><ChannelGroup title="Organic & Content Channels" items={["SEO", "Social Media", "Email", "WhatsApp", "Content Marketing", "Influencer"]} /><ChannelGroup title="Analytics & Conversion" items={["GA4", "Search Console", "Looker Studio", "Shopify", "CRM", "Conversion Rate Optimization"]} /></div></Container></section>
    <section id="process" className="consulting-light consulting-section"><Container className="common-container"><ConsultingHeading kicker="How we consult" title="No Advice Goes Out Until We Have Seen Your Actual Data" text="Four structured steps — built to move fast without skipping the depth that makes the output useful." /><div className="consulting-steps">{steps.map(([number, title, text], index) => <article key={number}><b>{number}</b><h3>{title}</h3><p>{text}</p>{index < 3 && <span>→</span>}</article>)}</div></Container></section>
    <section className="consulting-deliverables consulting-section"><Container className="common-container"><ConsultingHeading dark kicker="What you leave with" title="Strategy You Can Actually Use" text="Clear, documented thinking that helps your team make better decisions long after the session." /><div>{[["A clear diagnosis", "What is working, what is not, and why."], ["Prioritised roadmap", "The next actions that will create the biggest impact."], ["Channel strategy", "Where to invest, what to pause, and how to measure it."], ["Senior perspective", "Direct access to people who have seen the patterns before."]].map(([title, text]) => <article key={title}><i>✓</i><h3>{title}</h3><p>{text}</p></article>)}</div></Container></section>
    <section className="consulting-cta"><Container className="common-container text-center"><h2>Let&apos;s Talk About What Your<br />Marketing <em>Needs</em></h2><p>Tell us where you are and what you are trying to fix. We will tell you if we can help — and exactly how.</p><div><Link href="/contact" className="consulting-button">Get Free Consultation →</Link><Link href="/contact" className="consulting-button consulting-outline">Talk To The Team</Link></div></Container></section>
  </main>;
}

function Insight({ title, text }) { return <article><i /> <div><strong>{title}</strong><p>{text}</p></div></article>; }
function ConsultingHeading({ kicker, title, text, dark = false }) { return <div className={`consulting-heading ${dark ? "consulting-heading-dark" : ""}`}><p className="consulting-kicker">{kicker}</p><h2>{title}</h2>{text && <p>{text}</p>}</div>; }
function ChannelGroup({ title, items }) { return <div><h3>{title}</h3><p>{items.map(item => <span key={item}>● {item}</span>)}</p></div>; }
